### PR TITLE
* fixed @import with specific file name (see http://sass-lang.com/doc…

### PR DESCRIPTION
**Pull request by ndrew**
…umentation/file.SASS_REFERENCE.html#import for details)

* fixed loading commented imports

### CODE REVIEW

**Comment by ndrew** [comment]
I've fixed the direct import of scss files.
Also, there was a bug with gosass trying to build imports that were commented out — I've adjusted the regexp to handle such cases

**Comment by ysimonson** [comment]
Thanks, this is awesome! It looks like tests are failing at the moment - could you fix?

**Comment by ndrew** [comment]
my fault — forgot to commit the file needed for test. Should work now

**Comment by ysimonson** [comment]
OK to reopen and merge the PR?

**Pull request merged**
