### PR TITLE
An update to the watch mechanism to watch for directory additions and add them to the watch list.

### PR DESCRIPTION
**Pull request by OverclockedTim**

### CODE REVIEW

**Comment by ysimonson** [comment]
I'm not seeing this doing anything at the moment. Created a new directory and there was no log entry.

**Comment by OverclockedTim** [comment]
Hey Yusuf, that's odd. It was definitely working for me. Did you try adding sass files to the newly created directory?

**Comment by ysimonson** [comment]
I did. Haven't had time to debug why it's not triggering, but will try to take a closer look later this week.

**Comment by OverclockedTim** [comment]
Yeah, or just let me know your test steps.  I ran it again this morning, and I got the following log output after adding a new directory to my watched input direct "test", renaming the new directory to "blah" and then adding 01.simple.scss to blah: 

    [test/untitled folder] Adding newly created directory to watch list.
    [test/blah] Adding newly created directory to watch list.
    [test/blah/01.simple.scss] Compiled to output/blah/01.simple.css
    [test/blah/01.simple.scss] Compiled to output/blah/01.simple.css

**Comment by ysimonson** [comment]
OK, wrote a little bash script to test it out. Running this script on my computer outputs `Directory does not exists`.

    #!/bin/bash

    mkdir sass css

    gosass -input sass/ -output css/ -watch &
    PID=$!
    sleep 1

    mkdir sass/testdir
    sleep 1

    if [ -d "css/testdir" ]; then
        echo "Directory exists"
    else
        echo "Directory does not exists"
    fi


    kill $PID
    rm -r sass css

**Comment by OverclockedTim** [comment]
Hmm I probably wouldn't expect the output directory to get created until a sass file was placed in the input directory. I'll write a similar script with that addition and post the results a bit later today hopefully.

**Comment by OverclockedTim** [comment]
I ran the bash script and got the same results.

Then, I added a single line, 'touch sass/testdir/thingy.scss' for a full script of: 

#!/bin/bash

mkdir sass css

gosass -input sass/ -output css/ -watch &
PID=$!
sleep 1

mkdir sass/testdir
touch sass/testdir/thingy.scss
sleep 1

if [ -d "css/testdir" ]; then
    echo "Directory exists"
else
    echo "Directory does not exists"
fi


kill $PID
rm -r sass css

After the change, executing results in: 

Timothys-MBP:OverclockedTim palantar$ ./test.sh
[sass/testdir] Adding newly created directory to watch list.
[sass/testdir/thingy.scss] Compiled to css/testdir/thingy.css
Directory exists
Timothys-MBP:OverclockedTim palantar$

**Comment by OverclockedTim** [comment]
I'm starting to wonder if there might be some sort of compilation difference somehow. I uploaded my generated gosass (renamed to .txt to make github happy)
[gosass.txt](https://github.com/dailymuse/gosass/files/31521/gosass.txt) - built on a mid 2010 Macbook Pro running OSX 10.10 - hopefully it will be compatible.

**Comment by ysimonson** [comment]
I tried adding the touch but it didn't do anything.

They don't have the same hash, so they're not identical. But I'm not sure if that means anything - maybe the executables have metadata or something that prevent them from producing the exact same output between machines, or maybe even individual builds.

Without being able to get this functionality on my system, I'm going to have to reject.

**Pull request closed without merging**
